# Generated by Django 3.2 on 2023-12-18 14:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a post title', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(help_text='Enter a brief post description', max_length=200)),
                ('featured_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('additional_img1', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('additional_img2', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('additional_img3', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('additional_img4', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('additional_img5', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Enter the post text here')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Archived')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
