# Generated by Django 3.2 on 2023-12-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='user',
        ),
    ]
