# Generated by Django 3.2 on 2023-12-19 11:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231219_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='post_images/'),
        ),
    ]
