# Generated by Django 3.2 on 2023-12-22 22:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231219_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[850, 450], upload_to='p4/post_images/'),
        ),
    ]
