# Generated by Django 3.2 on 2024-01-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artclass',
            name='age_group',
            field=models.CharField(choices=[('5-7', '5-7 years old'), ('8-10', '8-10 years old')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artclass',
            name='duration',
            field=models.CharField(choices=[('5-7', '5-7 years old'), ('8-10', '8-10 years old')], help_text='Enter the class duration', max_length=10),
        ),
        migrations.AlterField(
            model_name='artclass',
            name='end_date',
            field=models.DateField(help_text='Select the end date'),
        ),
        migrations.AlterField(
            model_name='artclass',
            name='start_date',
            field=models.DateField(help_text='Select the start date'),
        ),
    ]
