# Generated by Django 3.2 on 2024-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20240101_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artclass',
            name='duration',
            field=models.CharField(choices=[('1', '1 hour'), ('1.5', '1.5 hours'), ('2', '2 hours')], help_text='Enter the class duration', max_length=10),
        ),
    ]
