# Generated by Django 3.2 on 2024-01-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_artclass_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='emg_contact_name',
            field=models.CharField(default='james', help_text='Enter the emergency contacts name', max_length=20),
            preserve_default=False,
        ),
    ]
