# Generated by Django 3.2 on 2024-01-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_emg_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Enter booking notes here'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid')], default=0),
        ),
    ]
