# Generated by Django 3.2 on 2024-01-03 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20240102_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='artclass',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Select the start time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_name',
            field=models.CharField(help_text='Enter name (letters only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(help_text='Enter number in the format XXX XXX XXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emg_contact_name',
            field=models.CharField(help_text='Enter name (letters only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emg_contact_number',
            field=models.CharField(help_text='Enter number in the format XXX XXX XXXX', max_length=20),
        ),
    ]
