# Generated by Django 3.2 on 2024-01-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20240103_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artclass',
            options={'ordering': ['-start_date']},
        ),
    ]
